### PR TITLE
feat(propagation): Generate spectrogram data and surfaces simultaneou…

### PR DESCRIPTION
**Pull request by mattwigway**
…sly to reduce computation time

We used to do propagation twice. This PR combines spectrogram data and surface calculation, which cuts total run time by 25% at the cost of forcing surface rebuild when destination data is changed.

I'll rebase in the morning.

### CODE REVIEW

**Comment by trevorgerhardt** [comment]
Oi, working off of old code there mate!

**Comment by trevorgerhardt** [comment]
Geez, I've been hanging out with too many Aussies 😝

**Comment by mattwigway** [comment]
@trevorgerhardt any additional comments here? Rebasing ended up really messy so I did a merge commit.

**Comment by trevorgerhardt** [comment]
Re-applied some commits and it looks good. Going to merge.

**Comment by mattwigway** [comment]
For future reference, what was wrong with how I merged?

**Comment by trevorgerhardt** [comment]
Changes were not reapplied correctly.

1. In this PR you had deleted a file, merging from dev brought it back.
2. My changes to the callback function of getSurfaceAndSpectrogramData were not reapplied.
3. I had removed the or clause in setting `from_name` and `to_name` because sometimes you don't want to show any (as @abyrd requested in taui)

**Pull request merged**
